// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace asp.net_youtube_course.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225023345_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MyProperty")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Long term hold",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "Great company"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Dividends are okay, could be better",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "Dividends"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Azure is growing fast",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2,
                            Title = "Cloud King"
                        },
                        new
                        {
                            Id = 4,
                            Content = "High risk high reward",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3,
                            Title = "Volatile"
                        },
                        new
                        {
                            Id = 5,
                            Content = "AWS is the money maker",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 4,
                            Title = "AWS"
                        },
                        new
                        {
                            Id = 6,
                            Content = "NVIDIA is leading the AI revolution",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 5,
                            Title = "AI Boom"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Google still dominates search",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 6,
                            Title = "Search Monopoly"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Betting big on the future",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 7,
                            Title = "Metaverse"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Safe haven asset",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 8,
                            Title = "Warren Buffett"
                        },
                        new
                        {
                            Id = 10,
                            Content = "New drugs are game changers",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 9,
                            Title = "Weight Loss"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Strong demand for chips",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 10,
                            Title = "Semiconductors"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Best managed bank",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 11,
                            Title = "Bank Leader"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Cashless society beneficiary",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 12,
                            Title = "Payments"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Low prices everyday",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 13,
                            Title = "Retail Giant"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Energy demand remains high",
                            IsDeleted = false,
                            MyProperty = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 14,
                            Title = "Oil & Gas"
                        });
                });

            modelBuilder.Entity("Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "APPLE INC",
                            Industry = "Technology",
                            IsDeleted = false,
                            LastDiv = 2.5m,
                            MarketCap = 3000000000L,
                            Purches = 250.00m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "MICROSOFT",
                            Industry = "Technology",
                            IsDeleted = false,
                            LastDiv = 3.0m,
                            MarketCap = 2500000000L,
                            Purches = 150.00m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Tesla Inc",
                            Industry = "Automotive",
                            IsDeleted = false,
                            LastDiv = 0.0m,
                            MarketCap = 600000000000L,
                            Purches = 180.00m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Amazon.com",
                            Industry = "Technology",
                            IsDeleted = false,
                            LastDiv = 0.0m,
                            MarketCap = 1500000000000L,
                            Purches = 140.00m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "NVIDIA Corp",
                            Industry = "Technology",
                            IsDeleted = false,
                            LastDiv = 0.16m,
                            MarketCap = 2000000000000L,
                            Purches = 800.00m,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Alphabet Inc",
                            Industry = "Technology",
                            IsDeleted = false,
                            LastDiv = 0.0m,
                            MarketCap = 1700000000000L,
                            Purches = 140.00m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Meta Platforms",
                            Industry = "Technology",
                            IsDeleted = false,
                            LastDiv = 0.50m,
                            MarketCap = 1200000000000L,
                            Purches = 480.00m,
                            Symbol = "META"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Berkshire Hathaway",
                            Industry = "Financial Services",
                            IsDeleted = false,
                            LastDiv = 0.0m,
                            MarketCap = 900000000000L,
                            Purches = 400.00m,
                            Symbol = "BRK.B"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Eli Lilly",
                            Industry = "Healthcare",
                            IsDeleted = false,
                            LastDiv = 1.30m,
                            MarketCap = 700000000000L,
                            Purches = 750.00m,
                            Symbol = "LLY"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Broadcom Inc",
                            Industry = "Technology",
                            IsDeleted = false,
                            LastDiv = 5.25m,
                            MarketCap = 600000000000L,
                            Purches = 1200.00m,
                            Symbol = "AVGO"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "JPMorgan Chase",
                            Industry = "Financial Services",
                            IsDeleted = false,
                            LastDiv = 1.05m,
                            MarketCap = 500000000000L,
                            Purches = 180.00m,
                            Symbol = "JPM"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Visa Inc",
                            Industry = "Financial Services",
                            IsDeleted = false,
                            LastDiv = 0.52m,
                            MarketCap = 550000000000L,
                            Purches = 280.00m,
                            Symbol = "V"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Walmart Inc",
                            Industry = "Consumer Defensive",
                            IsDeleted = false,
                            LastDiv = 0.20m,
                            MarketCap = 450000000000L,
                            Purches = 60.00m,
                            Symbol = "WMT"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Exxon Mobil",
                            Industry = "Energy",
                            IsDeleted = false,
                            LastDiv = 0.95m,
                            MarketCap = 400000000000L,
                            Purches = 105.00m,
                            Symbol = "XOM"
                        });
                });

            modelBuilder.Entity("Entities.Comments", b =>
                {
                    b.HasOne("Entities.Stock", "Stock")
                        .WithMany("Comment")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Entities.Stock", b =>
                {
                    b.Navigation("Comment");
                });
#pragma warning restore 612, 618
        }
    }
}
